export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD'
export const SET_USER_EMAIL = 'SET_USER_EMAIL'
