export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD'
export const SET_USER_EMAIL = 'SET_USER_EMAIL'
export const SET_QUESTION = 'SET_QUESTION'
export const WITHDRAW = 'WITHDRAW'
export const DEPOSIT = 'DEPOSIT'
export const INCREMENT_REMAINING_QUESTIONS = 'INCREMENT_REMAINING_QUESTIONS'
export const DECREMENT_REMAINING_QUESTIONS = 'DECREMENT_REMAINING_QUESTIONS'
export const INCREMENT_QUESTIONS_PER_ROUND = 'INCREMENT_QUESTIONS_PER_ROUND'
export const DECREMENT_QUESTIONS_PER_ROUND = 'DECREMENT_QUESTIONS_PER_ROUND'

export const QUESTIONS_PER_ROUND = 10
export const STARTING_CUBES = 6
