export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD'
export const SET_USER_EMAIL = 'SET_USER_EMAIL'
export const SET_QUESTION = 'SET_QUESTION'
export const WITHDRAW = 'WITHDRAW'
export const DEPOSIT = 'DEPOSIT'
export const ESTIMATE = 'ESTIMATE'
export const INCREMENT_CURRENT_QUESTION = 'INCREMENT_CURRENT_QUESTION'
export const INCREMENT_NUM_QUESTIONS = 'INCREMENT_NUM_QUESTIONS'
export const DECREMENT_NUM_QUESTIONS = 'DECREMENT_NUM_QUESTIONS'

export const QUESTIONS_PER_ROUND = 10
export const STARTING_CUBES = 6
